apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp
  namespace: monitoring
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: stepserg/nginx-diplom:latest
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: monitoring
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30700
