name: ci

on:
  push:
    branches: main

env:
  IMAGE_TAG: stepserg/nginx-app

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: stepanovsa061/test_app_diplom/Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}:any_commit
